#!/usr/bin/env Rscript

# Plot the DP>=10 partitioned IQ-TREE phylogram generated by
# align_and_run_partitioned_iqtree_dp10_Nmissing.sh.
#
# Outputs publication-ready PDF, PNG and SVG figures, plus a table recording
# the inferred plotting group assigned to every tip.

suppressPackageStartupMessages({
  library(ape)
  library(ggplot2)
  library(ggtree)
  library(dplyr)
  library(stringr)
  library(tibble)
})

args <- commandArgs(trailingOnly = TRUE)

default_tree <- "/group/sequencing/assembly/James/OsHV_annot/Align_raws/dp10_complete_CDS_sets/mafft_iqtree_partitioned_dp10/concatenated/OsHV_dp10_partitioned.treefile"
default_output <- "/group/sequencing/assembly/James/OsHV_annot/Align_raws/dp10_complete_CDS_sets/mafft_iqtree_partitioned_dp10/figures"

tree_file <- if (length(args) >= 1) args[[1]] else default_tree
output_dir <- if (length(args) >= 2) args[[2]] else default_output

if (!file.exists(tree_file)) {
  stop("Tree file does not exist: ", tree_file)
}
dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)

# ---------- User-adjustable appearance ----------
figure_width_mm <- 210
figure_height_mm <- 185
base_size <- 9
tip_font_size <- 2.7
support_symbol_size <- 2.2
label_offset_fraction <- 0.012

# Colours distinguish the study groups central to the sensitivity analysis.
group_colours <- c(
  "New South Wales" = "#0072B2",
  "South Australia" = "#E69F00",
  "Tasmania 2016-2019" = "#009E73",
  "Tasmania 2024" = "#D55E00",
  "New Zealand" = "#CC79A7",
  "Reference genome" = "#666666",
  "Other" = "#000000"
)

group_shapes <- c(
  "New South Wales" = 17,
  "South Australia" = 17,
  "Tasmania 2016-2019" = 17,
  "Tasmania 2024" = 17,
  "New Zealand" = 17,
  "Reference genome" = 16,
  "Other" = 16
)
# ------------------------------------------------

phy <- read.tree(tree_file)

# Remove duplicate reference sequence from the plotted tree. (Because AY is the refseq it is downloaded twice when doing a broad scan of genomes
tips_to_drop <- c("NC_005881.2")

missing_tips <- setdiff(tips_to_drop, phy$tip.label)

if (length(missing_tips) > 0) {
  warning(
    "The following requested tips were not found in the tree: ",
    paste(missing_tips, collapse = ", ")
  )
}

tips_present <- intersect(tips_to_drop, phy$tip.label)

if (length(tips_present) > 0) {
  phy <- ape::drop.tip(phy, tips_present)
  message(
    "Removed duplicate tip(s) from the plotted tree: ",
    paste(tips_present, collapse = ", ")
  )
}

# Midpoint-root the phylogram after removing the duplicate tip.
if (requireNamespace("phangorn", quietly = TRUE)) {
  phy <- phangorn::midpoint(phy)
} else {
  warning(
    "Package 'phangorn' is unavailable; ",
    "plotting the tree without midpoint rooting."
  )
}

# IQ-TREE may write internal labels as "SH-aLRT/UFBoot". This parser also
# supports single numeric labels, treating them as UFBoot only.
parse_support <- function(label) {
  if (is.na(label) || label == "") return(c(sh_alrt = NA_real_, ufboot = NA_real_))
  cleaned <- str_replace_all(label, "\\s", "")
  values <- suppressWarnings(as.numeric(unlist(str_split(cleaned, "/"))))
  if (length(values) >= 2) {
    return(c(sh_alrt = values[[1]], ufboot = values[[2]]))
  }
  if (length(values) == 1) {
    return(c(sh_alrt = NA_real_, ufboot = values[[1]]))
  }
  c(sh_alrt = NA_real_, ufboot = NA_real_)
}

node_support <- t(vapply(phy$node.label, parse_support, numeric(2))) |> as.data.frame()
node_support$node <- seq_len(phy$Nnode) + length(phy$tip.label)
node_support$support_class <- case_when(
  !is.na(node_support$sh_alrt) & !is.na(node_support$ufboot) &
    node_support$sh_alrt >= 95 & node_support$ufboot >= 95 ~ ">=95% both",
  !is.na(node_support$sh_alrt) & !is.na(node_support$ufboot) &
    node_support$sh_alrt >= 80 & node_support$ufboot >= 80 ~ ">=80% both",
  is.na(node_support$sh_alrt) & !is.na(node_support$ufboot) &
    node_support$ufboot >= 95 ~ ">=95% UFBoot",
  is.na(node_support$sh_alrt) & !is.na(node_support$ufboot) &
    node_support$ufboot >= 80 ~ ">=80% UFBoot",
  TRUE ~ NA_character_
)

# Classify tips by sample naming pattern. NZ SRA tips are recognized from the
# accessions used in the manuscript. All remaining accessions are references.
classify_tip <- function(label) {
  case_when(
    str_detect(label, "^OsHV_NSW_") ~ "New South Wales",
    str_detect(label, "^OsHV_SA_") ~ "South Australia",
    str_detect(label, "^OsHV_TAS_2024_") ~ "Tasmania 2024",
    str_detect(label, "^OsHV_TAS_(2016|2017|2018|2019)_") ~ "Tasmania 2016-2019",
    str_detect(label, "^SRR1421030[345]$") ~ "New Zealand",
    str_detect(label, "^OsHV_") ~ "Other",
    TRUE ~ "Reference genome"
  )
}

tip_data <- tibble(
  label = phy$tip.label,
  group = factor(vapply(phy$tip.label, classify_tip, character(1)), levels = names(group_colours))
)

write.table(
  tip_data,
  file = file.path(output_dir, "DP10_tree_tip_groups.tsv"),
  sep = "\t", quote = FALSE, row.names = FALSE
)

# Italic formatting is intentionally avoided because labels are isolate IDs and
# accession numbers rather than species names.
p <- ggtree(phy, linewidth = 0.45) %<+% tip_data

plot_data <- p$data
max_x <- max(plot_data$x, na.rm = TRUE)
label_offset <- max_x * label_offset_fraction

p <- p +
  geom_tippoint(aes(colour = group, shape = group), size = 2.25, stroke = 0.25) +
  geom_tiplab(aes(colour = group), size = tip_font_size, offset = label_offset,
              align = FALSE, linesize = 0.25, show.legend = FALSE) +
  scale_colour_manual(values = group_colours, drop = FALSE, name = NULL) +
  scale_shape_manual(values = group_shapes, drop = FALSE, name = NULL)

# Add support symbols at internal nodes. Closed squares show >=95% for both
# tests; open squares show >=80% for both tests. Single-value node labels are
# retained as UFBoot-only categories and drawn with circles to avoid implying
# that both tests were available.
p <- p %<+% node_support +
  geom_point2(
    aes(subset = !isTip & support_class == ">=95% both"),
    shape = 15, size = support_symbol_size, colour = "black"
  ) +
  geom_point2(
    aes(subset = !isTip & support_class == ">=80% both"),
    shape = 22, size = support_symbol_size, colour = "black", fill = "white", stroke = 0.55
  ) +
  geom_point2(
    aes(subset = !isTip & support_class == ">=95% UFBoot"),
    shape = 16, size = support_symbol_size - 0.2, colour = "black"
  ) +
  geom_point2(
    aes(subset = !isTip & support_class == ">=80% UFBoot"),
    shape = 21, size = support_symbol_size - 0.2, colour = "black", fill = "white", stroke = 0.55
  )

p <- p +
  xlab("Substitutions per site") +
  coord_cartesian(clip = "off") +
  theme_tree2(base_size = base_size) +
  theme(
    legend.position = "bottom",
    legend.direction = "horizontal",
    legend.box = "vertical",
    legend.text = element_text(size = 8),
    axis.title.x = element_text(size = 9, margin = margin(t = 5)),
    axis.text.x = element_text(size = 8),
    plot.margin = margin(5.5, 55, 5.5, 5.5)
  ) +
  guides(
    colour = guide_legend(nrow = 2, byrow = TRUE, override.aes = list(size = 3)),
    shape = guide_legend(nrow = 2, byrow = TRUE, override.aes = list(size = 3))
  )

pdf_file <- file.path(output_dir, "Figure_DP10_partitioned_core_gene_tree.pdf")
png_file <- file.path(output_dir, "Figure_DP10_partitioned_core_gene_tree.png")
svg_file <- file.path(output_dir, "Figure_DP10_partitioned_core_gene_tree.svg")

ggsave(pdf_file, p, width = figure_width_mm, height = figure_height_mm, units = "mm", device = cairo_pdf)
ggsave(png_file, p, width = figure_width_mm, height = figure_height_mm, units = "mm", dpi = 600, bg = "white")
if (requireNamespace("svglite", quietly = TRUE)) {
  ggsave(svg_file, p, width = figure_width_mm, height = figure_height_mm, units = "mm", device = svglite::svglite)
} else {
  warning("Package 'svglite' unavailable; SVG output was not generated.")
}

# Also save the midpoint-rooted tree used in the plot and its support table.
write.tree(phy, file = file.path(output_dir, "OsHV_dp10_partitioned_midpoint_rooted.treefile"))
write.table(
  node_support,
  file = file.path(output_dir, "DP10_tree_node_support.tsv"),
  sep = "\t", quote = FALSE, row.names = FALSE
)

message("Figure outputs written to: ", output_dir)
message("PDF: ", pdf_file)
message("PNG: ", png_file)
if (file.exists(svg_file)) message("SVG: ", svg_file)
